### ISSUE TITLE
合并视频经常提示出错

### ISSUE THREAD

**Issue by bingsunny0730** [271374667/VideoFusion#2]
选择的MP4视频均没问题且均是快速输出的选项设置，有以下问题：
1.将两个5s的短视频合并时等半天卡进度无响应，日志无动静。用过LosslessCut的合并却可以，难道过短的视频不支持合并？
2.电脑支持GPU加速，可在输出视频编码中选取
(1)“H264nvidia”会提示：
`CRITICAL | src.common.ffmpeg:run_command:193 - FFmpeg命令运行失败: "D:\VIDEOF~1\bin\ffmpeg.exe" -i "C:\Users\bingsunny\Downloads\Video\1222.mp4" -filter_complex "fps=fps=30,hqdn3d=4.0:3.0:6.0:4.5,deband,deblock=alpha=1:beta=1" -af "highpass=200,lowpass=3000,afftdn,aresample=44100:resampler=soxr:precision=28:osf=s16:dither_method=triangular" -c:a aac -b:a 44100 -strict experimental -vsync 1 -c:v h264_nvenc -qscale 15 "D:\VideoFusion\Temp\1222_output.mp4" -y, 错误信息: None`
(2)“H265”会提示还无法暂停运行：
`CRITICAL | src.common.ffmpeg:run_command:193 - FFmpeg命令运行失败: "D:/VideoFusion/bin/ffmpeg.exe" -fflags +genpts -i "D:\VideoFusion\Temp\1222_output.mp4" -c copy -bsf:v h264_mp4toannexb -vsync 2 -f mpegts "D:\VideoFusion\Temp\ts_files\1222_output.ts" -y, 错误信息: None`
试了H265intel、H265Nvidia也是类似的提示，只有H264是正常的，Ffmpeg的路径也已经设置好，这类出错问题该怎么解决好？

另外，建议主页当中右上方合并的通知提示可以设置几秒的时间暂留后自动关闭，消息多了长期停留还要手动逐个关闭，有点影响使用。

**Comment by 271374667** [comment]
很高兴看到您的issue
我观察到您的视频存放在C盘，有可能是因为C盘读写权限不够导致FFmpeg无法正确的读取视频的内容，也有可能OpenCV不支持您当前的视频格式，您可以尝试将视频重新编码再进行合并，我制作这个软件的初衷和LosslessCut之类的精细化剪辑工具不同，我是为了批量化去除视频黑边，纠正统一视频方向而制作，通常情况下视频的数量可能成百上千，视频合并以及压缩主要是为了能够更加方便的存放进移动设备

关于报错请尝试使用最新版本或者尝试手动执行命令，您也可以等待下一个重大版本的更新， 下一个新的大版本会使用更加流程化的代码代替现在面向过程的代码，同时会使用OpenCV大规模代替FFmpeg

界面相关的建议会在下一个版本中修改

如果您还有更多问题欢迎继续提问

**Comment by bingsunny0730** [comment]
感谢大佬指点。不过还是要说的是，目前用的是0.32.4，看来是某些MP4编码格式不能被opencv所识别导致无法合并 且无进度，与视频时长无关。按正常理解的话，不应该是只要符合导入的视频格式就能合并而无需理会编码格式的嘛？但在这里反而感觉有点突兀了，为了可以正常合并就需要满足opencv能识别指定编码格式的视频，如果不符合只能重编码，感觉这样有时既增加了使用门槛又增加转换的工作量。能否改善下？

另外，找了正常的视频，测试了一下，设置当中的“输出视频编码”还是只有H264及H264intel能正常使用，其余H264/H265 nvidia等等在此版本均会出现一合并必出错，都会提示FFmpeg命令运行失败的错误日志，依旧没能正常输出。

其实最初也是看中该软件的AI降噪及分辨率算法，只是以上的因素有所影响，能理解的，看来只能期待下个版本的更新吧。。

**Comment by 271374667** [comment]
新版本已经更新，欢迎使用最新版本进行尝试，优化了 H265 以及其他的编码器，在开始尝试之前需要先检查自己是否支持硬件编码，您可以在最新的文档中查看

https://271374667.github.io/VideoFusion/advanced_settings#%E8%BE%93%E5%87%BA%E8%A7%86%E9%A2%91%E7%BC%96%E7%A0%81
