### ISSUE TITLE
当我尝试使用源码在macOS运行时的问题

### ISSUE THREAD

**Issue by Sakana20** [271374667/VideoFusion#4]
![QQ20240913-103050](https://github.com/user-attachments/assets/b5ec7c32-150f-41ad-a544-4bafe7bb4188)
![QQ20240913-103103](https://github.com/user-attachments/assets/c9e0b055-73fc-45ad-b990-d39d9e0a0919)
![QQ20240913-103120](https://github.com/user-attachments/assets/9801e8c8-350a-4a1d-8ae8-a6b3d378685a)

我发现即使修改了config里面关于ffmpeg的路径软件依旧会寻找.exe的文件，然后提示文件不存在

**Comment by 271374667** [comment]
您好，因为源码里面我会让他去寻找后缀为.exe的文件，如果您想要在其他系统下运行您可以删除src/config里面176行的代码，将
```python
ffmpeg_file = ConfigItem("General", "FFmpeg路径", str(FFMPEG_FILE), FFmpegValidator())
```
改为
```python
ffmpeg_file = ConfigItem("General", "FFmpeg路径", str(您的ffmpeg路径), None)
```

注意，软件设置被运行在window下，其他环境可能会出现意想不到的情况，欢迎随时提问

**Comment by Sakana20** [comment]
修改之后提示
cd '/Users/yiranmobi/Desktop/VideoFusion-master/' && '/usr/local/bin/python3'  '/Users/yiranmobi/Desktop/VideoFusion-master/video_fusion.py'  && echo Exit status: $? && exit 1
yiranmobi@Sakana-iMac ~ % cd '/Users/yiranmobi/Desktop/VideoFusion-master/' && '/usr/local/bin/python3'  '/Users/yiranmobi/Desktop/VideoFusion-master/video_fusion.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/yiranmobi/Desktop/VideoFusion-master/video_fusion.py", line 5, in <module>
    from src.presenter.main_presenter import MainPresenter
  File "/Users/yiranmobi/Desktop/VideoFusion-master/src/presenter/main_presenter.py", line 1, in <module>
    from src.presenter.concate_presenter import ConcatePresenter
  File "/Users/yiranmobi/Desktop/VideoFusion-master/src/presenter/concate_presenter.py", line 13, in <module>
    from src.common.task_resumer.task_resumer_manager import TaskResumer, TaskResumerManager
  File "/Users/yiranmobi/Desktop/VideoFusion-master/src/common/task_resumer/task_resumer_manager.py", line 10, in <module>
    from src.utils import singleton
  File "/Users/yiranmobi/Desktop/VideoFusion-master/src/utils.py", line 18, in <module>
    from src.config import cfg
  File "/Users/yiranmobi/Desktop/VideoFusion-master/src/config.py", line 176
    ffmpeg_file = ConfigItem("General", "FFmpeg路径", str(/Users/yiranmobi/Desktop/VideoFusion-master/bin/ffmpeg), None)
                                                        ^
SyntaxError: invalid syntax

**Comment by 271374667** [comment]
您好，Python的语法规则需要将路径用引号包裹，正确的代码应该如下
```python
ffmpeg_file = ConfigItem("General", "FFmpeg路径", r"/Users/yiranmobi/Desktop/VideoFusion-master/bin/ffmpeg", None)
```

**Comment by Sakana20** [comment]
好像还是不可以
cd '/Users/yiranmobi/Desktop/VideoFusion-master/' && '/usr/local/bin/python3'  '/Users/yiranmobi/Desktop/VideoFusion-master/video_fusion.py'  && echo Exit status: $? && exit 1
yiranmobi@Sakana-iMac ~ % cd '/Users/yiranmobi/Desktop/VideoFusion-master/' && '/usr/local/bin/python3'  '/Users/yiranmobi/Desktop/VideoFusion-master/video_fusion.py'  && echo Exit status: $? && exit 1

📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

QCssParser::parseColorValue: Specified color with alpha value but no alpha given: 'rgba 0, 0, 0'
qt.qpa.fonts: Populating font family aliases took 165 ms. Replace uses of missing font family "Segoe UI" with one that exists to avoid this cost. 
No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
Failed to create QVideoSink "Not available"
Failed to initialize QMediaPlayer "Not available"
2024-09-13 11:03:17.511 | DEBUG    | src.common.task_resumer.task_resumer_manager:clear:86 - 清空任务恢复文件
2024-09-13 11:03:17.513 | ERROR    | src.common.ffmpeg_handler:__init__:30 - FFmpeg文件不存在: /Users/yiranmobi/Desktop/VideoFusion-master/bin/ffmpeg.exe
2024-09-13 11:03:17.513 | CRITICAL | __main__:main:17 - 程序发生了未知错误: FFmpeg文件不存在: /Users/yiranmobi/Desktop/VideoFusion-master/bin/ffmpeg.exe
2024-09-13 11:03:17.514 | DEBUG    | src.utils:delete_dir:303 - 删除临时文件夹:/Users/yiranmobi/Desktop/VideoFusion-master/Temp
Exit status: 0

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed

**Comment by 271374667** [comment]
在修改之后，重新运行之前需要先删除之前的config.json文件

**Comment by Sakana20** [comment]
嗯....我删除了重新运行还是提示
cd '/Users/yiranmobi/Desktop/VideoFusion-master/' && '/usr/local/bin/python3'  '/Users/yiranmobi/Desktop/VideoFusion-master/video_fusion.py'  && echo Exit status: $? && exit 1
yiranmobi@Sakana-iMac ~ % cd '/Users/yiranmobi/Desktop/VideoFusion-master/' && '/usr/local/bin/python3'  '/Users/yiranmobi/Desktop/VideoFusion-master/video_fusion.py'  && echo Exit status: $? && exit 1

📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

QCssParser::parseColorValue: Specified color with alpha value but no alpha given: 'rgba 0, 0, 0'
qt.qpa.fonts: Populating font family aliases took 170 ms. Replace uses of missing font family "Segoe UI" with one that exists to avoid this cost. 
No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
Failed to create QVideoSink "Not available"
Failed to initialize QMediaPlayer "Not available"
2024-09-13 11:08:08.031 | DEBUG    | src.common.task_resumer.task_resumer_manager:clear:86 - 清空任务恢复文件
2024-09-13 11:08:08.032 | ERROR    | src.common.ffmpeg_handler:__init__:30 - FFmpeg文件不存在: /Users/yiranmobi/Desktop/VideoFusion-master/bin/ffmpeg.exe
2024-09-13 11:08:08.033 | CRITICAL | __main__:main:17 - 程序发生了未知错误: FFmpeg文件不存在: /Users/yiranmobi/Desktop/VideoFusion-master/bin/ffmpeg.exe
2024-09-13 11:08:08.034 | DEBUG    | src.utils:delete_dir:303 - 删除临时文件夹:/Users/yiranmobi/Desktop/VideoFusion-master/Temp
Exit status: 0

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by 271374667** [comment]
抱歉，这是因为软件内置了一个FFmpeg.exe路径，所以您应该在config.json里面修改你的ffmpeg路径，就和你一开始做的那样

**Comment by Sakana20** [comment]
config.json里面重新生成的也不带.exe
{
    "Video": {
        "音频降噪": "arnndn=model=bin/cb.rnnn",
        "音频响度标准化": "",
        "音频采样率": 44100,
        "视频去色带": false,
        "视频去色块": false,
        "输出编码策略": "-c:v libx264 -crf 23 -preset slow -qcomp 0.5 -psy-rd 0.3:0 -aq-mode 2 -aq-strength 0.8",
        "输出文件路径": "/Users/yiranmobi/Desktop/VideoFusion-master/output",
        "补帧策略": 1,
        "缩放质量": "sinc",
        "视频去抖动": false,
        "黑边去除算法": 2,
        "目标视频帧率": 30,
        "视频降噪": "bilateral",
        "输出视频分辨率": 2,
        "去黑边采样帧数": 500
    },
    "AI": {
        "人声分离算法": 0,
        "自动剪辑": false
    },
    "OpenCV": {
        "自动调整视频亮度对比度": false,
        "超分辨率算法": 0,
        "视频白平衡": false
    },
    "General": {
        "完成后删除临时目录": true,
        "FFmpeg路径": "/Users/yiranmobi/Desktop/VideoFusion-master/bin/ffmpeg",
        "是否合并视频": true,
        "预览视频自动播放": false,
        "预览视频帧": 1,
        "预览视频是否去黑边": false,
        "临时目录": "/Users/yiranmobi/Desktop/VideoFusion-master/Temp",
        "视频处理引擎": 0
    },
    "QFluentWidgets": {
        "ThemeColor": "#ff009faa",
        "ThemeMode": "Light"
    }
}

**Comment by 271374667** [comment]
那看起来要改一些其他地方的代码，未来版本加入的AI功能我是直接做成 exe 来调用的，所以可能 VideoFusion 在 Mac 上不支持，因为本人比较穷，没有 Mac 设备，所以没法进行测试和开发，未来有钱了，买了 Mac ，说不定会考虑支持 Mac

抱歉啦~

**Comment by Sakana20** [comment]
好的 没关系 感谢您
